# Generated by Django 2.2.4 on 2019-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('speciality', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('speciality', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('priceperhour', models.FloatField(default=0)),
                ('available_from', models.DateField(null=True)),
                ('available_to', models.DateField(null=True)),
            ],
        ),
    ]
