# Generated by Django 2.2.4 on 2019-09-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeroffer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specialistoffer',
            name='name',
        ),
    ]
