# Generated by Django 2.2.4 on 2019-09-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projekt1', '0002_auto_20190904_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistoffer',
            name='available_to',
        ),
        migrations.AddField(
            model_name='customeroffer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistoffer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeroffer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='specialistoffer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
